version: "3.7"

services:
  shiny:
    container_name: '${COMPOSE_PROJECT_NAME}'
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    user: 'shiny'
    env_file: .env
    ports:
      - '${HOST_PORT_NUMBER}:3839'
    volumes:
      - 'shiny_logs:/var/log/shiny-server'
      - '${CSV_DATA_LOCATION}:/data'
    command:
      # I have added the rscript here so that the user does not need to 
      # worry about creating the duckdb dataset. Obviously, creating this as 
      # separate step is needed to achieve better performance.
      bash -c "R -e 'renv::restore();' && Rscript app/data/convert_data_to_duckdb.R && /usr/bin/shiny-server"

volumes:
  shiny_logs:
